### ISSUE TITLE
Bot responds to /u/scripture_bot, but not u/scripture_bot

### ISSUE THREAD

**Issue by mwfpope** [MatthewDaffern/redditbot#2]
u/scripture_bot (without the leading backslash) is a valid way to tag a user, but the bot expects the leading backslash. It won't respond without it.

**Comment by MatthewDaffern** [comment]
I'll just drop the / since I'm doing a string comparison.

**Comment by MatthewDaffern** [comment]
I do a string comprehension now. 

`if String in var`
