### ISSUE TITLE
[ESV only] When a book starts with a number (or is Song of Solomon), it pastes the whole chapter

### ISSUE THREAD

**Issue by mwfpope** [MatthewDaffern/redditbot#4]
See https://www.reddit.com/r/scripturebot/comments/9h29mh/test_20180918/

When the reference gets parsed, it's not looking for a specific format. Rather, it counts the number of words after the user mention, so if there's a number before the book name, then the counting gets thrown off, it doesn't find any verse numbers, and it thinks someone is requesting the whole chapter.

**Comment by MatthewDaffern** [comment]
I fixed the parser to dynamically strip the username, bible version, chapter and verse after locating the query in a comment. It'll respond properly to queries now.
